apiVersion: v1
kind: List
metadata:
  name: puppetserverca
items:
## IMAGESTREAM ##
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: build-puppetserverca-docker-image
      name: rhel7
    spec:
      tags:
        - from:
            kind: DockerImage
            name: 'registry.access.redhat.com/rhel:latest'
          generation: 2
          importPolicy: {}
          name: latest
          referencePolicy:
            type: Source
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: build-puppetserverca-docker-image
      name: puppetserverca
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: build-puppetserverca-code
      name: puppetserverca-code
## BUILDCONFIG ##
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        app: build-puppetserverca-docker-image
      name: build-puppetserverca-docker-image
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: 'puppetserverca:latest'
      source:
        git:
          ref: andrei_ca
          uri: 'https://github.com/andrei-asan/docker-puppetserver.git'
        type: Git
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: 'rhel7:latest'
        type: Docker
## BUILDCONFIG code ##
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        app: build-puppetserverca-code
      name: build-puppetserverca-code
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: 'puppetserverca-code:latest'
      source:
        git:
          uri: 'git@github.com:cegeka/puppet-monorepo.git'
          ref: 'puppet5'
        sourceSecret:
          name: github-deploykey
        type: Git
      strategy:
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: 'puppetserverca:latest'
        type: Source
      triggers:
        - imageChange:
          type: ImageChange
## DEPLOYMENTCONFIG ##
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: puppetserverca-code
      name: puppetserverca-code
    spec:
      replicas: 1
      selector:
        app: puppetserverca-code
        deploymentconfig: puppetserverca-code
      template:
        metadata:
          labels:
            app: puppetserverca-code
            deploymentconfig: puppetserverca-code
        spec:
          containers:
            - imagePullPolicy: Always
              image: 'puppetserverca-code:latest'
              name: puppetserverca-code
              ports:
                - containerPort: 8140
                  protocol: TCP
              volumeMounts:
                - mountPath: /certs
                  name: cert-volume
                  readOnly: true
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /status/v1/services
                  port: 8140
                  scheme: HTTPS
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 10
              livenessProbe:
                failureThreshold: 3
                initialDelaySeconds: 10
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 8140
                timeoutSeconds: 1
          volumes:
            - name: cert-volume
              secret:
                defaultMode: 420
                secretName: puppetca-certificates
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - puppetserverca-code
            from:
              kind: ImageStreamTag
              name: 'puppetserverca-code:latest'
          type: ImageChange

## SERVICE ##
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: puppetserverca
      name: puppetserverca
    spec:
      ports:
        - name: 443-tcp
          port: 443
          protocol: TCP
          targetPort: 8140
      selector:
        deploymentconfig: puppetserverca
## ROUTE ##
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: puppetserverca
      name: puppetserverca
    spec:
      host: openshift-puppetmasterca.cegeka.be
      port:
        targetPort: 443-tcp
      tls:
        termination: passthrough
      to:
        kind: Service
        name: puppetserverca
